### ISSUE TITLE
req.language vs req.i18n.language

### ISSUE THREAD

**Issue by allaire** [i18next/i18next-express-middleware#162] opened 2018-10-10 18:44 UTC
From what I understand `req.language`, is the language when the request comes in the middleware, and `req.i18n.language` is the most up to date version of the current language (like when an update occurs by `changeLanguage`). 

I got bit by this when in a route I was triggering `req.i18n.changeLanguage('fr')`. I expected `locals.language` to be `fr` in in my template, but instead I got `en`, since this was the language of the initial request.

Should we clarify this somewhere in the README?

**Comment by jamuhl** [comment] 2018-10-10 21:15
hm...the problem is locals.language gets set here in the middleware and while we update the req.language we do not update the locals.language...https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L15

guess we could update that...PR would be welcome

beside that why you need to call changeLanguage? there is no need to call that -> you should either use the detector build in or add a custom detection for your case -> so when handle function gets called it can use the detector to get the language -> not having to change that in a later middleware....

**Comment by allaire** [comment] 2018-10-11 13:42
@jamuhl I do it like this because I'm using the cookie detector so I don't have to write a custom detector on both server side and client side. Maybe it would be possible to do it either way, but I'm satisfied with what I have currently (it's a single page app with React on the frontend).

For the PR, is repeating:

```
if (res.locals) {
  res.locals.language = lng;
  res.locals.languageDir = i18next.dir(lng);
}
```

in the `languageChanged` callback an acceptable solution?

**Comment by jamuhl** [comment] 2018-10-11 14:01
Having a custom detector like: https://github.com/i18next/i18next-express-middleware#adding-own-detection-functionality should not break the cookie detection and exchanging with client

yes...the PR you describe is acceptable and will be merged with a big thank you ;)

**Comment by jamuhl** [comment] 2018-10-12 07:05
guess this could be closed - the PR was merged. If still relevant or running into other issues - feel free to reopen

**Closed by jamuhl** 2018-10-12 07:05 UTC
