### ISSUE TITLE
Example from README failing

### ISSUE THREAD

**Issue by docnoe** [i18next/i18next-express-middleware#2] opened 2015-12-09 13:42 UTC
Hi!

I tried to set up a server the way it is described in the README.md, but I get an immediate error:

```
TypeError: Cannot read property 'languageDetector' of undefined
    at /xyz/myproject/node_modules/i18next-express-middleware/lib/index.js:36:37
    at Layer.handle [as handle_request] (/xyz/myproject/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/xyz/myproject/node_modules/express/lib/router/index.js:312:13)
    at /xyz/myproject/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/xyz/myproject/node_modules/express/lib/router/index.js:330:12)
    at next (/xyz/myproject/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/xyz/myproject/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/xyz/myproject/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/xyz/myproject/node_modules/express/lib/router/index.js:312:13)
    at /xyz/myproject/node_modules/express/lib/router/index.js:280:7
```

Any ideas?

**Comment by jamuhl** [comment] 2015-12-10 08:01
seems i missed something, when the module is used without language detection plugin. Will be fixed asap.

For now just add the detector as described here: https://github.com/i18next/i18next-express-middleware#language-detection

**Comment by jamuhl** [comment] 2015-12-11 15:40
did you initialize i18next instance? seems not.

**Comment by jamuhl** [comment] 2015-12-17 14:48
initializing i18next will solve this issue. feel free to reopen if not the case.

**Comment by newmips** [comment] 2015-12-30 10:34
Hi docnoe, jamuhl,

I encounter the same issue... My init sequence in server.js is :
```javascript
var i18next = require('i18next');
var middleware = require('i18next-express-middleware');
i18next.init({ lng: "fr" });
app.use(middleware.handle(i18next, {removeLngFromUrl: false}));
```

When opening a page, I encounter the issue :
```javascript
TypeError: Cannot read property 'languageDetector' of undefined
```

Do you know how to up i18next properly ? Thank you.

**Comment by jamuhl** [comment] 2015-12-30 12:04
will need to check this again. meanwhile just add the language detector...you will need to add that anyway. https://github.com/i18next/i18next-express-middleware#language-detection

PR would be welcome.

**Comment by newmips** [comment] 2016-01-10 20:12
I have finally switched to another solution... It's maybe not the best one, but it seems to be working and might help some google crawlers.

```javascript
var i18next = require('i18next');
var FilesystemBackend = require('i18next-node-fs-backend');
var sprintf = require('i18next-sprintf-postprocessor');
var i18nextMiddleware = require('i18next-express-middleware');
options = {
	lng: "fr",
	debug: false,
  fallbackLng: false,
  load:'unspecific',
	backend: {
		// path where resources get loaded from
		loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',

		// path to post missing resources
		addPath: __dirname + '/locales/{{lng}}/{{ns}}.missing.json',

		// jsonIndent to use when storing json files
		jsonIndent: 2
	}
};

i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(FilesystemBackend)
  .use(sprintf)
  .init(options);

app.use(i18nextMiddleware.handle(i18next)); // expose req.t with fixed lng
app.post('/locales/:lng/translation.json', i18nextMiddleware.missingKeyHandler(i18next)); // serves missing key route for consumers (browser)
app.get('/locales/:lng/translation.json', i18nextMiddleware.getResourcesHandler(i18next)); // serves resources for consumers (browser)
```

**Comment by jamuhl** [comment] 2016-02-22 13:36
still can't really reproduce it in my configuration.

**Closed by jamuhl** 2016-02-22 13:36 UTC
